[package]
name = "papete"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
rustlearn = "0.5"
serde = "1.0"
serde_json = "1.0"
serialport = "4.2"